import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Form from "../components/Form";
const Home: NextPage = () => {
  return (
    <div className="bg-[#FCFFE7] h-screen">
      <Head>
        <title>StreaX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex justify-center ">
        <Form />
      </div>
    </div>
  );
};

export default Home;
